apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-sep10-3-py312 
  janus-idp.io/tekton: rag-sep10-3-py312
  backstage.io/kubernetes-id: rag-sep10-3-py312
  backstage.io/kubernetes-namespace: rag-sep10-3-py312 
  app.kubernetes.io/part-of: rag-sep10-3-py312
resources: 
- application-dev.yaml