apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rag-sep10-3-py312
  janus-idp.io/tekton: rag-sep10-3-py312
  backstage.io/kubernetes-id: rag-sep10-3-py312
  backstage.io/kubernetes-namespace: rag-sep10-3-py312 
  app.kubernetes.io/part-of: rag-sep10-3-py312
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- deployment-database.yaml
- service-database.yaml
- database-config.yaml
- rhoai/
